version: "3"
services:
  react-app: 
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: api-server
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - DATABASE_URL = mongodb://localhost/scholars-db
      - TOKEN_SECRET = turibaallrightreserved
      - REFRESH_SECRET = IrefreshAllthetime
      - SCOPUS_API_KEY= 0014eeab132901ee1ee41fe32f932325
      - SCOPUS_INSTTOKEN = e99a2ba023214e4a002284c423b4c8c9
      - GOOGLE_SCHOLAR_API_KEY = c94122db80d618830b9612cd1d610d5bdf75bc6b202087e03307b81706f43f98
      - DB_URL = mongodb://adminTuriba:admin123@ac-fzmazuz-shard-00-00.edwkivr.mongodb.net:27017,ac-fzmazuz-shard-00-01.edwkivr.mongodb.net:27017,ac-fzmazuz-shard-00-02.edwkivr.mongodb.net:27017/scholars-db?ssl=true&replicaSet=atlas-fkhg4c-shard-0&authSource=admin&retryWrites=true&w=majority
    networks:
      - mern-app
  mongo:
    image: my-mongo
    ports:
      - "28017:27017"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local